# api_client_view:
#     path: member/api-client
#     defaults: { _controller: WebkulApiBundle:Api:clientView }
#     methods: [GET,POST]
# api_client_xhr:
#     path:     member/client
#     defaults: { _controller: WebkulApiBundle:Api:clientXhr }
#     methods: [GET,POST,PUT]
# api_client_edit_xhr:
#     path: member/client/{id}
#     defaults: { _controller: WebkulApiBundle:Api:clientXhr }
#     methods: [PUT]
# access_token_xhr:
#     path:     member/access-token
#     defaults: { _controller: WebkulApiBundle:Api:accessTokenXhr }
#     methods: [GET,POST]
# access_token_edit_xhr:
#     path:     member/access-token/{id}
#     defaults: { _controller: WebkulApiBundle:Api:accessTokenXhr }
#     methods: [PUT,PATCH,DELETE]
# access_token_clean:
#     path: member/access-token/clean
#     defaults: { _controller:WebkulApiBundle:Api:accessTokenXhr }
#     methods: [DELETE]
# # can change to api route
# api_company_signup_rest:
#     path: company/signup.{format}
#     defaults: { _controller:WebkulApiBundle:User\UserApi:signupRest , format: json }
#     methods: [POST]

uvdesk_api_bundle_public_routing_resources:
    resource: "routes/TicketRestRouting.yaml"
    prefix:   /
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%