# services:
#     api.user.service:
#         class: Webkul\ApiBundle\Services\ApiUserService
#         arguments: ['@doctrine.orm.entity_manager']
#     api.default.service:
#         class: Webkul\ApiBundle\Services\ApiDefaultService
#         arguments: [@doctrine.orm.entity_manager,@user.service]
#     # ratelimit
#     # mybundle.listener.rate_limit_generate_key:
#     #     class: Webkul\ApiBundle\Listener\RateLimitGenerateKeyListener
#     #     tags:
#     #         - { name: kernel.event_listener, event: 'ratelimit.generate.key', method: 'onGenerateKey' }
#     oauth_event_listener:
#         class:  Webkul\ApiBundle\Listener\OAuthEventListener
#         arguments: [@user.service,@security.context]
#         tags:
#             - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
#             - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }
#             - { name: kernel.event_listener, event: kernel.response, method: modifyApiResponse }

#     api.token.service:
#         arguments: [@user.service,@security.context,@doctrine.orm.entity_manager]
#         class: Webkul\ApiBundle\Services\ApiTokenListener