# Tickets list
helpdesk_api_tickets:
    path:  tickets
    controller: Webkul\UVDesk\ApiBundle\Controller\Ticket\TicketApiController::ticketListRestAction
    methods:  [GET]

# Ticket view   
helpdesk_api_show_ticket:
    path:     /ticket/{ticketId}
    controller: Webkul\UVDesk\ApiBundle\Controller\Ticket\TicketApiController::viewTicketRestAction
    methods:  [GET]

# Delete Ticket  
helpdesk_api_trash_ticket:
    path:     /ticket/{ticketId}/trash
    controller: Webkul\UVDesk\ApiBundle\Controller\Ticket\TicketApiController::deleteTicketRestAction
    methods:  [PUT]
    
# Assign agent to ticket
helpdesk_api_assign_agent_to_ticket:
    path:   /ticket/{ticketId}/agent
    controller: Webkul\UVDesk\ApiBundle\Controller\Ticket\TicketApiController::assignAgentRestAction
    methods: [PUT]


